const seaAttractionDict = {
    'Aquatopia': 958,
    'Indy Jones Adventure: Temple of the Crystal Skull': 922,
    'Electric Railway (American Waterfront)': 952,
    'Electric Railway (Port Discovery)': 949,
    'Caravan Carousel': 964,
    "Sindbad's Storybook Voyage": 961,
    "Jasmine's Flying Carpet": 916,
    'Jumping Jellyfish': 973,
    "Skuttle's Scooter": 970,
    "Journey to the Center of the Earth": 925,
    'Soarin: Fantastic Flight': 913,
    'Turtle Talk': 994,
    'Toy Story Mania': 910,
    'Transit Steamer Line (American Waterfront)': 940,
    'Transit Steamer Line (Mediterranean Harbour)': 937,
    'Transit Steamer Line (Lost River Delta)': 943,
    'Nemo and Friends Sea Rider': 997,
    'Big City Vehicle': 955,
    'Fortress Exploration': 988,
    'Leonardo Challenge': 991,
    "Flounder's Flying Fish": 967,
    'Blowfish Balloon Race': 976,
    'Magic Lamp Theatre': 934,
    'Mermaid Lagoon Theatre': 919,
    'Raging Sprits': 982,
    'Whirlpool': 979,
    'Venetian Gondola': 946,
    '20,000 Leagues Under the Sea': 928,
  };
  export default seaAttractionDict;